version: "3"
services:
  db_postgres:
    image: postgres
    container_name: db_postgres
    restart: always
    ports: 
      - 1234:5432
    env_file:
      - .env
    volumes:
      - pg_volume:/var/lib/postgresql/data
  
  node_app:
    container_name: node_app_klafkbank
    build: .
    ports:
      - 5000:5000
    depends_on:
      - db_postgres
    env_file:
      - .env

volumes:
  pg_volume: